// ═══════════════════════════════════════════════════
// Guide Steps – Struktur ohne Texte
// Texte kommen vom LLM oder Fallback
// ═══════════════════════════════════════════════════

import type { GuideStep } from './guideTypes';

export const ONBOARDING_STEPS: GuideStep[] = [
  {
    id: 'welcome',
    targetSelector: '#tab-profil',
    fallbackSelector: '.app-content-main',
    waitFor: 'any',
    waitTimeout: 4000,
    contextKeys: ['userName', 'isFirstVisit'],
    skipIfMissing: false,
  },
  {
    id: 'profile',
    targetSelector: '#profil-avatar',
    fallbackSelector: '#tab-profil',
    requiredState: { hasProfile: true },
    waitFor: 'any',
    waitTimeout: 6000,
    contextKeys: ['hasProfile', 'userName'],
    skipIfMissing: true,
  },
  {
    id: 'score-button',
    targetSelector: '#btn-compute-score',
    fallbackSelector: '#tab-profil',
    requiredState: { hasProfile: true },
    waitFor: 'any',
    waitTimeout: 8000,
    contextKeys: ['hasScore'],
    skipIfMissing: true,
  },
  {
    id: 'score-intro',
    targetSelector: '#card-score-card',
    fallbackSelector: '#tab-report',
    requiredState: { hasScore: true },
    waitFor: 'any',
    waitTimeout: 6000,
    contextKeys: ['hasScore', 'scoreValue'],
    skipIfMissing: true,
  },
  {
    id: 'report-overview',
    targetSelector: '#tab-report',
    fallbackSelector: '.app-content-main',
    requiredState: { hasReport: true },
    waitFor: 'any',
    waitTimeout: 6000,
    contextKeys: ['hasReport', 'reportClaimCount'],
    skipIfMissing: true,
  },
  {
    id: 'discovery-hint',
    targetSelector: '.discovery-card-item:first-child',
    fallbackSelector: '#tab-report',
    requiredState: { hasReport: true },
    waitFor: 'any',
    waitTimeout: 6000,
    contextKeys: ['reportClaimCount'],
    skipIfMissing: true,
  },
  {
    id: 'studio',
    targetSelector: '#tab-studio',
    fallbackSelector: '.app-content-main',
    waitFor: 'any',
    waitTimeout: 8000,
    contextKeys: ['availablePersonas'],
    skipIfMissing: false,
  },
  {
    id: 'personas-intro',
    targetSelector: '#persona-row',
    fallbackSelector: '#tab-studio',
    waitFor: 'any',
    waitTimeout: 6000,
    contextKeys: ['availablePersonas', 'lastActivePersona'],
    skipIfMissing: true,
  },
  {
    id: 'sidebar-timeline',
    targetSelector: '#sidebar-timeline',
    fallbackSelector: '.app-content-main',
    waitFor: 'any',
    waitTimeout: 6000,
    contextKeys: ['timelineEntryCount'],
    skipIfMissing: true,
  },
  {
    id: 'soul-cards',
    targetSelector: '#sidebar-soul-cards',
    fallbackSelector: '#sidebar-timeline',
    requiredState: { hasSoulCards: true },
    waitFor: 'any',
    waitTimeout: 6000,
    contextKeys: ['soulCardCount'],
    skipIfMissing: true,
  },
  {
    id: 'farewell',
    targetSelector: '#tab-studio',
    fallbackSelector: '.app-content-main',
    waitFor: 'any',
    waitTimeout: 4000,
    contextKeys: ['userName', 'hasScore', 'soulCardCount'],
    skipIfMissing: false,
  },
];
