// Public API for module M05. No deep imports allowed outside this module.
export type { NumerologyEngine } from './lib/numerologyEngine';
export { buildNumerologyRequestFromProfile, computeNumerology } from './lib/numerologyEngine';
export { NumerologyCard } from './ui/NumerologyCard';
export { ChakraBar } from './ui/ChakraBar';
export { BiorhythmCurve } from './ui/BiorhythmCurve';
export { TarotDayCard } from './ui/TarotDayCard';
export { DailyAffirmations } from './ui/DailyAffirmations';
export { YearForecast } from './ui/YearForecast';
export { LifePathDetail } from './ui/LifePathDetail';
export { LifePinnacles } from './ui/LifePinnacles';
export { ChallengeNumbers } from './ui/ChallengeNumbers';
export { NumerologyRadar } from './ui/NumerologyRadar';
export { BirthstoneCard } from './ui/BirthstoneCard';
export { KarmicDebts } from './ui/KarmicDebts';
export { IdealPartnerHints } from './ui/IdealPartnerHints';
export { SoulTypeCard } from './ui/SoulTypeCard';
export { SoulSigil } from './ui/SoulSigil';
export { BirthMoonPhase } from './ui/BirthMoonPhase';
export { PersonalityCard } from './ui/PersonalityCard';
export { SoulIntention } from './ui/SoulIntention';
export { YearCalendar } from './ui/YearCalendar';
export { SoulDossier } from './ui/SoulDossier';
export { StrengthsAnalysis } from './ui/StrengthsAnalysis';
export { LuckyNumbers } from './ui/LuckyNumbers';
export { SoulColors } from './ui/SoulColors';
export { SoulJourney } from './ui/SoulJourney';
export { TimeCapsulle } from './ui/TimeCapsulle';
export { SoulMantra } from './ui/SoulMantra';
export { ShadowSide } from './ui/ShadowSide';
export { LifeMission } from './ui/LifeMission';
export { YearClock } from './ui/YearClock';
export { SoulContract } from './ui/SoulContract';
export { DreamArchive } from './ui/DreamArchive';
export { TreeOfLife } from './ui/TreeOfLife';
