// Public API for module M08. No deep imports allowed outside this module.
export type { StudioEngine } from './lib/studioEngine';
export { StubStudioEngine } from './lib/stubStudio';
export { SeatBadge } from './ui/SeatBadge';
export { TurnsView } from './ui/TurnsView';
export { StudioPanel } from './ui/StudioPanel';
export { StudioPage } from './ui/StudioPage';
export { LilithEyes } from './ui/LilithEyes';
export type { LilithEyeState, LilithEyeIntensity } from './ui/LilithEyes';
export { LilithAvatar } from './ui/LilithAvatar';
export { LilithPortrait } from './ui/LilithPortrait';
export { MayaAvatar } from './ui/MayaAvatar';
export { MayaPortrait } from './ui/MayaPortrait';
export { getLilithIntensity, setLilithIntensity } from './lib/lilithGate';
export type { LilithIntensity } from './lib/lilithGate';
export { PersonaSoloChat } from './ui/PersonaSoloChat';
export { loadChatHistory, appendMessage, clearChatHistory } from './lib/chatHistory';
export type { ChatMessage } from './lib/chatHistory';
export { updateSensitivity, shouldDowngradeIntensity, shouldTriggerMayaHandoff, getSensitivityState, resetSensitivity } from './lib/sensitivityTracker';
export type { SensitivityState } from './lib/sensitivityTracker';
export { detectToxicity, isBlocked, activateBlock, clearBlock, getBlockRemainingMs, evaluateMessage } from './lib/toxicityGuard';
export type { ToxicitySeverity, ModerationResult } from './lib/toxicityGuard';
export { loadUserMemory, addMemoryEntry, addStrike, getBanStatus, buildMemoryContext, clearUserMemory, getUserMemoryEntries, getStrikeRecord } from './lib/userMemory';
export type { MemoryEntry, MemoryEntryType, Sentiment, StrikeRecord, UserMemoryStore } from './lib/userMemory';
export { extractInsights, checkMilestone } from './lib/insightExtractor';
export { getLastPersona, setLastPersona } from './lib/personaPersist';
export { parseResponse, parseSoulCard, VALID_COMMANDS } from './lib/commandParser';
export type { MayaCommand, MayaCommandType, TourStep, ParsedResponse, SoulCardProposal } from './lib/commandParser';
export { createCommandBus, sleep } from './lib/commandBus';
export type { CommandBus, CommandDispatcher } from './lib/commandBus';
export type { MayaCommandCallbacks } from './ui/PersonaSoloChat';
export { LiveSigil } from './ui/LiveSigil';
export type { SigilState } from './ui/LiveSigil';
export { PersonaPreview } from './ui/PersonaPreview';
export { OracleMode } from './ui/OracleMode';
